#!/bin/sh

set -e
ANSI_RED='\033[0;31m'
ANSI_GREEN='\033[0;32m'
ANSI_YELLOW='\033[1;33m'
ANSI_RESET='\033[0m'

PATH_PROJECT=/var/www/findfolks
PATH_PUBLIC=${PATH_PROJECT}/public
PATH_CONFIG=${PATH_PROJECT}/config

case "$1" in
    configure)
        echo "\n ${ANSI_YELLOW} Running post-install... ${ANSI_RESET} \n"

        echo "Checking _ENV config... "
        if [ -e "${PATH_CONFIG}/common.conf" ]; then
            echo "${ANSI_GREEN} COMMON.CONF file found ${ANSI_RESET}";
        else
            echo "${ANSI_RED} COMMON.CONF file not found! ${ANSI_RESET}" ;
        fi

        echo "Making symlinks"
        ln -sf ${PATH_PUBLIC}/favicon/favicon.ico ${PATH_PUBLIC}/favicon.ico
        ln -sf ${PATH_PUBLIC}/favicon/apple-touch-icon.png ${PATH_PUBLIC}/apple-touch-icon-precomposed.png
        ln -sf ${PATH_PUBLIC}/favicon/android-chrome-192x192.png ${PATH_PUBLIC}/android-chrome-192x192.png
        ln -sf ${PATH_PUBLIC}/favicon/android-chrome-512x512.png ${PATH_PUBLIC}/android-chrome-512x512.png
        echo "  Ok"

        echo " Building /robots.txt file..."
        php ${PATH_PROJECT}/admin.tools/tool.postinst.php --make:robots
        echo "  Ok"

        echo "Fixing access rights..."
        chown -R www-data:www-data ${PATH_PROJECT}
        echo "${ANSI_GREEN} Ok. ${ANSI_RESET}"

        echo
        echo "${ANSI_YELLOW} ... post-install finished. ${ANSI_RESET}"
        echo

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
